import { CADModel } from '../types';

export const SAMPLE_MODELS: CADModel[] = [
  {
    id: 'sample-l-shape',
    name: '1. L-Profil (Stupňovitý blok)',
    difficulty: 'lehká',
    description: 'Základní stupňovité těleso ve tvaru L. Ideální pro první seznámení s nárysem, půdorysem a bokorysem.',
    fileType: 'procedural',
    proceduralId: 'l_shape',
    isSample: true,
    createdAt: 1700000001,
  },
  {
    id: 'sample-wedge-groove',
    name: '2. Klínový blok s drážkou',
    difficulty: 'lehká',
    description: 'Těleso se šikmou rozměrovou plochou (klínem) a podélným vybráním. Šikmá plocha se zobrazuje v půdorysu i bokorysu.',
    fileType: 'procedural',
    proceduralId: 'wedge_groove',
    isSample: true,
    createdAt: 1700000002,
  },
  {
    id: 'sample-u-block-hole',
    name: '3. U-Profil s válcovým otvorem',
    difficulty: 'střední',
    description: 'Strojní U-blok s přesným kruhovým otvorem. Vykresluje v nárysu a bokorysu tenké čárkované skryté hrany.',
    fileType: 'procedural',
    proceduralId: 'u_block_hole',
    isSample: true,
    createdAt: 1700000003,
  },
  {
    id: 'sample-stepped-pyramid',
    name: '4. Stupňovité těleso se zkosením',
    difficulty: 'střední',
    description: 'Víceúrovňový hranol s čelním zkosením a postranními výřezy. Prověřuje správnost čtení viditelných obrysů.',
    fileType: 'procedural',
    proceduralId: 'stepped_pyramid',
    isSample: true,
    createdAt: 1700000004,
  },
  {
    id: 'sample-fusion-tslot',
    name: '5. CAD T-drážka z Fusion 360',
    difficulty: 'těžká',
    description: 'Složitý CAD model vyrobený ve Fusion 360 s T-drážkou, zkosenými hranami a vnitřním vybráním pro náročné cvičení.',
    fileType: 'procedural',
    proceduralId: 'fusion_tslot_complex',
    isSample: true,
    createdAt: 1700000005,
  },
];
